let obj={
    data:[{
        name:'首页',
        key:'0',
        path:'/admin/home',
        type:'home'
    },
    {
        name:'主题管理',
        key:'1',
        type:'apple',
        children:[
            {
                name:'banner管理',
                key:'1-0',
                type:'behance-square',
                children:[{
                name:'banner列表',
                key:'1-0-0',
                path:'/admin/banner/list',
                type:'unordered-list'
            },
            {
                name:'banner上传',
                key:'1-0-1',
                path:'/admin/banner/add',
                type:'file-add'
            }
            ]
            },
            {
                name:'广告位管理',
                key:'1-1',
                type:'reddit'
            },
            {
                name:'标题栏管理',
                key:'1-2',
                type:'coffee'
            }
        ]
    },
    {
        name:'商品管理',
        key:'2',
        type:'skin',
        children:[
            {
               name:'商品添加',
               path:'/admin/goodsadd' ,
               key:'2-0',
               type:'folder-add'
            },
            {
                name:'商品列表',
                path:'/admin/goodsabout' ,
                key:'2-1',
                type:'ordered-list'
             },
        ]
    },
    {
        name:'用户管理',
        key:'3',
        type:'tool',
        children:[
            {
                name:'客户管理',
                key:'3-0',
                path:'/admin/usermanage',
                type:'usergroup-add'
            },
            {
                name:'管理员管理',
                key:'3-1',
                path:'/admin/adminmanage',
                type:'user-add'
            }
        ]
    }
]
}
export default obj